name: eosdart
description: EOSIO-based blockchain RPC API client in Dart language
version: 0.5.3
homepage: https://github.com/primes-network/eosdart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3
  json_annotation: ^4.0.1
  pointycastle: ^3.1.3
  eosdart_ecc: ^0.4.4
#  path: ^1.4.1

dev_dependencies:
  test: ^1.17.9
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
